import tkinter
#creating a tkinter window
def open_window():
    window=tkinter.Tk()
    background_image1 = tkinter.PhotoImage(file="HELP.png")
    background = tkinter.Label(window, image=background_image1, bd=0)
    background.pack()
    window.mainloop()
root = tkinter.Tk()
root.configure(background="black")
root.title("ASTEROIDS")
root.geometry("900x700")
background_image = tkinter.PhotoImage(file="SP.png")
background = tkinter.Label(root, image=background_image, bd=0)
background.pack()
frame = tkinter.Frame(root)
frame.pack()
button1=tkinter.Button(frame,height="10",width="20",text="EASY",bg="green")
button1.pack(side=tkinter.LEFT)
button1=tkinter.Button(frame,height="10",width="20",text="ITNERMEDIATE",bg="yellow")
button1.pack(side=tkinter.LEFT)
button = tkinter.Button(frame,height="10",width="20",text="MAD LEVEL",bg="RED")
button.pack(side=tkinter.LEFT)

button = tkinter.Button(frame,height="10",width="20",text="HELP??",bg="ORANGE",command=open_window)
button.pack(side=tkinter.LEFT)
button = tkinter.Button(frame,height="10",width="20",text="QUIT",bg="PURPLE",command=root.destroy)
button.pack(side=tkinter.RIGHT)
root.mainloop()
